### ISSUE TITLE
Filtros por situação da terafa

### ISSUE THREAD

**Issue by liomoura** [alexmonteiro/Redmine-Monitoring-Controlling#107]
Primeiramente queria parabenizar pelo belíssimo trabalho realizado neste plugin, em segundo gostaria de saber se é possível haver um filtro para o gráfico de situação da tarefa?, hoje tenho vários tipos poluindo meu status report, segue print abaixo. 

![image](https://cloud.githubusercontent.com/assets/10420467/6854945/3fe39654-d3d3-11e4-9579-6d217f981a98.png)

Desde já obrigado!

**Comment by liomoura** [comment]
Alex, existe alguma pretensão de realizar novas features neste plugin, ou você só irá encorporar novos Pull Requests ? 

Atenciosamente,

**Comment by alexmonteiro** [comment]
Por enquanto não há previsão de retorno de implementação de melhorias, os pull requests que aceito são somente aqueles que tenho certeza que não afetará o projeto pois os mariores é preciso fazer testes e não estou com disponibilidade.

**Comment by liomoura** [comment]
Ok, obrigado!
