### ISSUE TITLE
Incompatibilidade com Redmine 3.0.x

### ISSUE THREAD

**Issue by isabelacristinaterra** [alexmonteiro/Redmine-Monitoring-Controlling#110]
Olá, existe alguma incompatibilidade com o Redmine 3.0.x?
No meu caso estou usando a 3.0.4 e o plugin não está funcionando.
Me desculpe se aqui não for lugar para dúvidas do tipo, foi o único modo que encontrei para entrar em contato.
Obrigada desde já.

**Comment by alexmonteiro** [comment]
O plugin foi desenvolvido e testado até a versão 2.0.x, conforme especificado no branch master. Alguns usuários já instalaram o plugin até a versão 2.4.6 do Redmine, e funcionou. Geralmente o problema que ocorre na instalação é resolvido renomeando o diretório do plugin para redmine_monitoring_controlling. Espero que funcione.

**Comment by isabelacristinaterra** [comment]
Oi Alex! Era isso mesmo!
Agradeço a ajuda!
