### ISSUE TITLE
Don´t Work on Redmine 3.1.0.stable

### ISSUE THREAD

**Issue by darioajr** [alexmonteiro/Redmine-Monitoring-Controlling#111]
![redmine1](https://cloud.githubusercontent.com/assets/7606/9585242/0ae84662-4fec-11e5-91b7-55e57c1abf4a.png)

**Comment by alexmonteiro** [comment]
Rename the instalation folder to redmine_monitoring_controlling and restart the server then try it again.

**Comment by darioajr** [comment]
Work´s fine, Thanks...
