### ISSUE TITLE
assigned and issues by situation & browser problemas

### ISSUE THREAD

**Issue by KammutierSpule** [alexmonteiro/Redmine-Monitoring-Controlling#32]
This chart doesn't appear. I need to scroll the bottom bar to make it appear.

I also have problems in IE, it doesn't show: Time Management  and Human Resource Management 

Any problem with my setup?

**Comment by saran110313** [comment]
I'm receiving this error originating from fabric.js

Uncaught TypeError: Cannot call method 'apply' of undefined

function klass() {
(ln: 3135) --> this.initialize.apply(this, arguments);
}

**Comment by saran110313** [comment]
Uncaught TypeError: Failed to execute 'drawImage' on 'CanvasRenderingContext2D': The provided value is not of type '(HTMLImageElement or HTMLVideoElement or HTMLCanvasElement or ImageBitmap)'
how to solve this error in fabric.js
