### ISSUE TITLE
Show graphics by filter options

### ISSUE THREAD

**Issue by flavioportela** [alexmonteiro/Redmine-Monitoring-Controlling#69]
Could you implements an option to filter by VERSION, or SITUATION (with many itens selection possibility) ?
The graphs show us only the consolidate informations. When we work with versions it is unvaluable.

**Comment by FranJose** [comment]
+1, by the way, do you have a planning for this feature?

**Comment by Shruthiss** [comment]
Please do answer

**Comment by alexmonteiro** [comment]
I would like to improve the plugin, but nowadays I don't have time to spend on this project. I will keep this issue in mind.

**Comment by Shruthiss** [comment]
But is the issue is solved?

On Fri, Aug 7, 2015 at 9:02 PM, Alexander Monteiro <notifications@github.com

**Comment by Shruthiss** [comment]
But is the issue resolved??
